Update patch set 1
Patch Set 1:

recheck
07:10:35 Summarizing 3 Failures:
07:10:35 
07:10:35 [Fail] [sig-network] Service endpoints latency [It] should not be very high  [Conformance] 
07:10:35 /jenkins/workspace/iessp/iaas/kubernetes/kubernetes_amd64/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service_latency.go:121
07:10:35 
07:10:35 [Fail] [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] [It] should perform canary updates and phased rolling updates of template modifications [Conformance] 
07:10:35 /jenkins/workspace/iessp/iaas/kubernetes/kubernetes_amd64/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:339
07:10:35 
07:10:35 [Fail] [sig-scheduling] SchedulerPredicates [Serial] [BeforeEach] validates that NodeSelector is respected if not matching  [Conformance] 
07:10:35 /jenkins/workspace/iessp/iaas/kubernetes/kubernetes_amd64/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:87
07:10:35 
07:10:35 Ran 162 of 890 Specs in 11111.571 seconds
07:10:35 FAIL! -- 159 Passed | 3 Failed | 0 Pending | 728 Skipped --- FAIL: TestE2E (11111.74s)

Patch-set: 1
Reviewer: YAMAMOTO Takashi <1002897@d5d70762-12d0-45a1-890d-524b12d3f735>